### ISSUE TITLE
[Proposal] Optional on LoginActivity fields

### ISSUE THREAD

**Issue by truongnmt** [ankane/authtrail#24]
Hi there! First, thanks for your awesome work! 

I'm using AuthTrail for a while now. To fit my use case, I'm looking for a workaround to:
1. Delete fields I don't use: `city region latitude longitude`
I got this error when delete those fields, obviously:
> Error performing AuthTrail::GeocodeJob (Job ID: d7bef36a-5fe6-468f-a70b-79353f11bff9) from Async(default) in 2.55ms: ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'city' in 'field list': UPDATE `login_activities` SET `city` = NULL, `region` = NULL, `country` = 'United States', `latitude` = 0.0, `longitude` = 0.0 WHERE `login_activities`.`id` = 1):
2. Add extra custom field(s) to LoginActivity. Other than fields from Devise, we want to save some extra field(s).

What do you think about this? Thanks a lot!

**Comment by ankane** [comment]
Hey @truongnmt,

1. Making fields optional sounds good to me. We already do this for [geocoding](https://github.com/ankane/authtrail/blob/fd410b97707cebf61bf8dde09dcfd6fc8c856d53/app/jobs/auth_trail/geocode_job.rb#L20), so happy to accept a PR.
2. Where are the extra fields populated from? There was a proposal to add extra fields from the request object in #21. It wasn't merge, but happy to revisit.

**Comment by truongnmt** [comment]
1. Sound good to me.
2. #21 doesn't look really clean, messy I would say. For flexibility I thinking a way to add field(s), not just one, each field have a custom way to retrieve data. Kind of each fields has it proc.

🤔

**Comment by ankane** [comment]
Cleaning up issues, but feel free to submit PRs.

**Comment by ankane** [comment]
fwiw, there's now a `request_info_method` option on master.

**Comment by truongnmt** [comment]
Wow! Thanks a lot! 💯💯💯
