### ISSUE TITLE
Error Devise::Models::Trailable

### ISSUE THREAD

**Issue by carlosver17** [ankane/authtrail#32]
Hello @ankane !

I'm trying to use the "account_activity" branch to get the signout log but after add: "devise :trailable" the server doesn't work, instead shows the following error: `const_get': uninitialized constant Devise::Models::Trailable (NameError).

Any ideas?

Regards!

**Comment by ankane** [comment]
Hey @carlosver17, try including `authtrail` after `devise` in your Gemfile. I'm guessing this line isn't being run: https://github.com/ankane/authtrail/blob/5e0b290ffa591886256ba0218d6ef9a520cc292e/lib/authtrail.rb#L14-L16

**Comment by carlosver17** [comment]
Hello @ankane,

Actually authtrail gem is the last one on my Gemfile.

Regards!

**Comment by ankane** [comment]
I'm not sure what it could be besides Authtrail being required before Devise. I'd confirm Devise doesn't have `require: false` in your Gemfile, and then try forking the gem to debug.

**Comment by ankane** [comment]
Cleaning up issues
