### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ankane** [ankane/authtrail#33]
0.5

- [x] Remove `activerecord` from gemspec - #46 

1.0

- [ ] Expand to more activities - sign outs, email changes, password changes, password reset requests, locks, unlocks, and confirmations - `activity_type` branch
- [ ] Rename model to `AuthTrail::Activity` (existing users can have it use `login_activities` table) - `authtrail_activity` branch

**Comment by renchap** [comment]
Great gem, thanks for it!
Do you think it would be in scope to allow callbacks on specific activities (once they are complete, geocoding has been done…)?

Use case: reporting this activity to an external system (analytics, security-analysis…).

**Comment by ankane** [comment]
Hey @renchap, it's an interesting idea. Users can currently customize the `track_method` for login attempts (for SIEM integration, analytics, etc) and add callbacks to the Geocode job (since it uses Active Job), so I'm a bit hesitant to add more functionality around it.

**Comment by DiegoOrejuela** [comment]
@ankane maybe you could consider allowing a custom class to be used as the tracking model.

**Comment by ankane** [comment]
Hey @DiegoOrejuela, you can use the `track_method` option for that.
