### ISSUE TITLE
use with mongodb

### ISSUE THREAD

**Issue by nrankin** [ankane/authtrail#46]
Hi, this gem works with mongodb, however it pulls in activerecord as a dependency which isn't ideal in this scenario.
Is there a possibility of making it so that activerecord can be configured by the using app rather than the default?

**Comment by ankane** [comment]
Hey @nrankin, thanks for the suggestion! Will make this part of the 0.5.0 release (don't have a timeline, but you should be able to fork and remove [this line](https://github.com/ankane/authtrail/blob/c18b5a724d1fa1df30b616de7f77468b16e83c46/authtrail.gemspec#L19) in the meantime).

**Comment by nrankin** [comment]
hey @ankane thanks for that suggestion! I wasn't sure if there would be any ramifications from removing that 😅

**Comment by ankane** [comment]
Removed in the commit above. Thanks again for the suggestion.
