### ISSUE TITLE
Race conditions in Sidekiq

### ISSUE THREAD

**Issue by davidlowry** [ankane/authtrail#47]
Hi there

I have an issue where my Geocoding jobs arent being completed by Sidekiq and are returning a deserialization error as follows. Is there any way to hint to the authtrail geocoder 'service' to make those actions only after the create _commit_ action, or to indicate they should wait for a while before occuring?

`
just now | default | AuthTrail::GeocodeJob | {"_aj_globalid"=>"gid://app/LoginActivity/619929"} | ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find LoginActivity with 'id'=619929
`
`ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find LoginActivity with 'id'=619929`

Thanks
David

**Comment by ankane** [comment]
Hey @davidlowry, the job isn't enqueued until [after the transaction is committed](https://github.com/ankane/authtrail/blob/f2e91f52f55595687d44e83ffb921c76f4a2b8d9/lib/authtrail.rb#L55-L56). You can customize the `track_method` as needed.
