### ISSUE TITLE
customize auth stategy detector

### ISSUE THREAD

**Issue by skreib** [ankane/authtrail#49]
the private method is used for detecting auth strategies
```ruby
  def detect_strategy(auth)
    strategy = auth.env["omniauth.auth"]["provider"] if auth.env["omniauth.auth"]
    strategy ||= auth.winning_strategy.class.name.split("::").last.underscore if auth.winning_strategy
    strategy ||= "database_authenticatable"
    strategy
  end
```

The problem appears with the device-jwt gem due to incorrect parsing.
For example, `Warden::JWTAuth::Strategy` transforms into `strategy`.

Expected result:
`Warden::JWTAuth::Strategy` => `jwtauth_strategy`
or
`Warden::JWTAuth::Strategy` => `jwtauth`

Can some custom strategy parser be added, for example, by initializer config?

**Comment by ankane** [comment]
Hi @skreib, you can use `transform_method` for this.

```ruby
AuthTrail.transform_method = lambda do |data, request|
  # customize as needed
  data[:strategy] = request.env["warden"].winning_strategy.class.name
end
```
