### ISSUE TITLE
Rubocop issue

### ISSUE THREAD

**Issue by alec-c4** [ankane/authtrail#52]
Hey!
I've found that migration is having the following issue with a rubocop - Rails/ThreeStateBooleanColumn in this line

```ruby
      t.boolean :success
```

I've fixed it with following

```ruby
      t.boolean :success, null: false, default: true

```
But it looks like there are possible false negative cases, what do you think?

**Comment by ankane** [comment]
Hi @alec-c4, thanks for sharing. However, I don't think a change is needed.
