### ISSUE TITLE
Bug after signin

### ISSUE THREAD

**Issue by lethunder** [ankane/authtrail#53]
Hello guys,

i have this when i enable geocode after signin
Failed enqueuing AuthTrail::GeocodeJob to GoodJob(low_priority): ActiveModel::MissingAttributeError (can't write unknown attribute active_job_id)

rails-7.1.3.2
ruby 3.2.2
authtrail-0.5.0

**Comment by ankane** [comment]
Hi @lethunder, check out https://github.com/bensheldon/good_job/issues/1216.

**Comment by lethunder** [comment]
Thanks @ankane . It works now
